[project]
name = "vision-encoder-comparison"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "datasets>=2.19.1",
    "huggingface-hub>=1.11.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pillow>=12.1.1",
    "safetensors>=0.7.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=5.5.4",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"
